# This workflow will install Python dependencies and run tests with a python on ubuntu without GPU
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    pull-requests: write
    contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_cpu.txt ]; then pip install -r requirements_cpu.txt; fi

    - name: Add project root to PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Test with pytest
      id: test
      run: |
        pip install pytest pytest-cov
        pip install .
        pytest

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6

    - name: Update README with test Badge
      run: |
        sed -i '/.. Pytest Test:Begin/,/.. Pytest Test:End/c\.. Pytest Test:Begin\n\n.. |test| image:: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests%20with%20python%203.9-3.11.yml/badge.svg?branch=main\n   :target: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests%20with%20python%203.9-3.11.yml\n   :alt: test\n\n.. Pytest Test:End' ./README.rst
      
    - name: Commit & Push changes to Readme
      uses: actions-js/push@master
      with:
        message: Update test result on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
