# This workflow will install Python dependencies and run tests with a python on ubuntu without GPU
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    pull-requests: write
    contents: write
    id-token: write

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_cpu.txt ]; then pip install -r requirements_cpu.txt; fi

    - name: Add project root to PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Test with pytest
      id: test
      run: |
        pip install pytest pytest-cov
        pip install -e .
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ > pytest-coverage.txt || echo "pytest_failed=true" >> $GITHUB_ENV


    - name: Pytest coverage comment
      if: env.pytest_failed != 'true'
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        hide-report: true

    - name: Update README with Coverage Badge
      if: env.pytest_failed != 'true'
      run: |
        sed -i '/.. Pytest Coverage\/Status Comment:Begin/,/.. Pytest Coverage\/Status Comment:End/c\.. Pytest Coverage\/Status Comment:Begin\n\n.. |build| image:: https://img.shields.io/badge/Coverage-${{ steps.coverageComment.outputs.coverage }}-${{ steps.coverageComment.outputs.color }}.svg\n   :target: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/test_update_coverage_on_readme.yml\n   :alt: Coverage\n\n.. Pytest Coverage\/Status Comment:End' ./README.rst
      
    - name: Update README with Failed Status Badge
      if: env.pytest_failed == 'true'
      run: |
        sed -i '/.. Pytest Coverage\/Status Comment:Begin/,/.. Pytest Coverage\/Status Comment:End/c\.. Pytest Coverage\/Status Comment:Begin\n\n.. |build| image:: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/tests.yml/badge.svg?event=push\n    :target: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/test_update_coverage_on_readme.yml\n    :alt: Tests Failed\n\n.. Pytest Coverage\/Status Comment:End' ./README.rst
      
    - name: Commit & Push changes to Readme
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
