

    - name: Test with pytest
      id: test
      run: |
        pip install pytest pytest-cov
        pip install .
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ > pytest-coverage.txt 


    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        hide-report: true

    - name: Update README with Coverage Badge
      run: |
        sed -i '/.. Pytest Coverage Comment:Begin/,/.. Pytest Coverage Comment:End/c\.. Pytest Coverage Comment:Begin\n\n.. |coverage| image:: https://img.shields.io/badge/Coverage-${{ steps.coverageComment.outputs.coverage }}25-${{ steps.coverageComment.outputs.color }}.svg\n   :target: https://github.com/c3di/ImgDataConvertCodeGen/actions/workflows/update_coverage_on_readme.yml\n   :alt: Coverage\n\n.. Pytest Coverage Comment:End' ./README.rst

      
    - name: Commit & Push changes to Readme
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
